from pydantic import BaseModel, ConfigDict, Field


class ProductBase(BaseModel):
    item_name: str = Field(
        min_length=1,
        max_length=255,
        description="Name of the webshop product.",
        examples=["morzsaporszivo"],
    )
    quantity: int = Field(
        ge=0,
        description="Available stock quantity. It cannot be negative.",
        examples=[12],
    )
    price: int = Field(
        gt=0,
        description="Product price stored as a whole number.",
        examples=[24900],
    )
    category: str | None = Field(
        default=None,
        max_length=255,
        description="Optional product category.",
        examples=["haztartasi gep"],
    )


class ProductCreate(ProductBase):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "item_name": "morzsaporszivo",
                "quantity": 12,
                "price": 24900,
                "category": "haztartasi gep",
            },
        },
    )


class ProductUpdate(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "quantity": 7,
                "category": "elektronika",
            },
        },
    )

    item_name: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="New product name. Leave it out to keep the current name.",
        examples=["akkumulatoros csavarbehajto"],
    )
    quantity: int | None = Field(
        default=None,
        ge=0,
        description=(
            "New stock quantity. Leave it out to keep the current one."
        ),
        examples=[7],
    )
    price: int | None = Field(
        default=None,
        gt=0,
        description="New product price. Leave it out to keep the current one.",
        examples=[19900],
    )
    category: str | None = Field(
        default=None,
        max_length=255,
        description="New optional product category.",
        examples=["elektronika"],
    )


class ProductResponse(ProductBase):
    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "f3b38d70-c07d-11f0-9d64-0242ac120002",
                "item_name": "morzsaporszivo",
                "quantity": 12,
                "price": 24900,
                "category": "haztartasi gep",
            },
        },
    )

    id: str = Field(
        description="Unique product identifier generated by the application.",
        examples=["f3b38d70-c07d-11f0-9d64-0242ac120002"],
    )
