from typing import Annotated, Any

from fastapi import APIRouter, HTTPException, Path, status

from app.api.deps import ProductRepositoryDep
from app.models.product import Product
from app.repositories.product_repository import ProductRepository
from app.schemas.product import ProductCreate, ProductResponse, ProductUpdate

router = APIRouter()
ProductId = Annotated[
    str,
    Path(
        description="Unique product identifier generated by the application.",
        examples=["f3b38d70-c07d-11f0-9d64-0242ac120002"],
    ),
]
NOT_FOUND_RESPONSE: dict[int | str, dict[str, Any]] = {
    status.HTTP_404_NOT_FOUND: {
        "description": "Product not found.",
    },
}


@router.get(
    "/",
    response_model=list[ProductResponse],
    summary="List products",
    description="Return every product stored in the webshop inventory.",
    response_description="List of webshop products.",
)
async def list_products(repository: ProductRepositoryDep) -> list[Product]:
    return await repository.get_all()


@router.get(
    "/{product_id}",
    response_model=ProductResponse,
    summary="Get product by id",
    description="Return one product by its generated unique identifier.",
    response_description="The requested webshop product.",
    responses=NOT_FOUND_RESPONSE,
)
async def get_product(
    product_id: ProductId,
    repository: ProductRepositoryDep,
) -> Product:
    product = await repository.get_by_id(product_id)

    if product is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Product not found",
        )

    return product


@router.post(
    "/",
    response_model=ProductResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create product",
    description=(
        "Create a new webshop product. The id is generated automatically."
    ),
    response_description="The created webshop product with its generated id.",
)
async def create_product(
    product_data: ProductCreate,
    repository: ProductRepositoryDep,
) -> Product:
    return await repository.create(product_data)


@router.put(
    "/{product_id}",
    response_model=ProductResponse,
    summary="Update product",
    description=(
        "Update one or more fields of an existing product by its id."
    ),
    response_description="The updated webshop product.",
    responses=NOT_FOUND_RESPONSE,
)
async def update_product(
    product_id: ProductId,
    product_data: ProductUpdate,
    repository: ProductRepositoryDep,
) -> Product:
    return await update_product_data(product_id, product_data, repository)


async def update_product_data(
    product_id: str,
    product_data: ProductUpdate,
    repository: ProductRepository,
) -> Product:
    product = await repository.update(product_id, product_data)

    if product is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Product not found",
        )

    return product


@router.delete(
    "/{product_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete product",
    description="Delete an existing product from the webshop inventory.",
    response_description="The product was deleted successfully.",
    responses=NOT_FOUND_RESPONSE,
)
async def delete_product(
    product_id: ProductId,
    repository: ProductRepositoryDep,
) -> None:
    deleted = await repository.delete(product_id)

    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Product not found",
        )
